### ISSUE TITLE
Same issue as https://github.com/Franticware/SGDK_wine/issues/1#issue-797766868

### ISSUE THREAD

**Issue by ReaderGuy42** [Franticware/SGDK_wine#5]
#1 I have the same issue as this person.

> Additional info is needed.
> 
> 1. What is your SGDK version?
> 
> 2. What linux distro are you using? I have tested it only on Manjaro.
> 
> 3. What is the output of:
> 
> ```
> cd /home/gustavo/apps/sgdk/bin
> sh generate_wine.sh
> ```
> 
> ?
> 
> 4. Have you tried building an existing sample, e.g.:
> 
> ```
> cd /home/gustavo/apps/sgdk/bin/sample/sprite
> make GDK=/home/gustavo/apps/sgdk -f /home/gustavo/apps/sgdk/makefile_wine.gen
> ```
> 
> ?

_Originally posted by @Franticware in https://github.com/Franticware/SGDK_wine/issues/1#issuecomment-770425302_

Hi, I'm having the exact same issue.
I'm on Linux Mint 20.2, with SGDK-1.62.

`sh generate_wine.sh` spits out:

`ar
as
bintos
cc1
cp
cpp
gcc
gdb
ld
lto1
lto-wrapper
mac68k
make
mkdir
nm2wch
nm
objcopy
objdump
pcmtoraw
rm
sh
sizebnd
size
sjasm
xgmtool`

And I can't find bin/sample/sprite.
Any ideas?

**Comment by Franticware** [comment]
What is the output of
`make GDK=/path/to/sgdk -f /path/to/sgdk/makefile_wine.gen`
?

**Comment by ReaderGuy42** [comment]
that tells me 
`/opt/SGDK-1.62/bin# make GDK=/opt/SGDK-1.62 -f /opt/SGDK-1.62/makefile_wine.gen
mkdir -p src/boot
mkdir -p out
/opt/SGDK-1.62/bin/gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -Wno-main -Wno-unused-parameter -fno-builtin -Iinc -Isrc -Ires -I/opt/SGDK-1.62/inc -I/opt/SGDK-1.62/res -B/opt/SGDK-1.62/bin -c src/boot/rom_head.c -o out/rom_head.o
wine: '/opt/SGDK-1.62/bin' is not owned by you, refusing to create a configuration directory there
make: *** [/opt/SGDK-1.62/makefile_wine.gen:166: out/rom_head.o] Error 1
root@ME_USER:/opt/SGDK-1.62/bin# 
`

**Comment by ReaderGuy42** [comment]
That happened btw in the "elevated" Terminal.

**Comment by ReaderGuy42** [comment]
I figured out how to change ownership of the directory and am now waiting for WINE to finish updating. (a little WINE window is telling me `The Wine configuration in /path/to/SGDK/bin/.wineconf is being updated, please wait...`

**Comment by ReaderGuy42** [comment]
I'm trying to follow along[ this tutorial by the way](https://www.ohsat.com/tutorial/megapong/megapong-1/), though obviously I haven't gotten very far, since I can't even get anything to compile/make.
I just tried `./bin/make -f makelib.gen` as per that tutirial, and got the (repeating) error message `wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.`

This is probably related to the above error, so I'm just going to wait for your reply. Thanks for your help already!!

**Comment by ReaderGuy42** [comment]
Ok, thanks to somone on reddit, I've solved it. I think the issue was that I hadn't "cd"-ed to the game directory. I got the "hello world" to work now :)
Thanks
