### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nicomegadrive** [Franticware/SGDK_wine#8]
Hi,

First thanks for your dev, I could compile at first thanks to it. Today I tried again after following a tutorial, and despite not having any error or just try to compile a basic template, it'll return this :

make GDK=~/Téléchargements/SGDK-1.80 -f ~/Téléchargements/SGDK-1.80/makefile_wine.gen
mkdir -p src/boot
mkdir -p out
/home/nicolas/Téléchargements/SGDK-1.80/bin/gcc -B/home/nicolas/Téléchargements/SGDK-1.80/bin -n -T /home/nicolas/Téléchargements/SGDK-1.80/md.ld -nostdlib out/sega.o @out/cmd_ /home/nicolas/Téléchargements/SGDK-1.80/lib/libmd.a /home/nicolas/Téléchargements/SGDK-1.80/lib/libgcc.a -o out/rom.out -Wl,--gc-sections
C:\users\nicolas\Temp\ccSorTYf.ltrans2.ltrans.o: In function `_reset_entry':
<artificial>:(.text+0xb0e): undefined reference to `main'
C:\users\nicolas\Temp\ccSorTYf.ltrans2.ltrans.o: In function `_start_entry':
<artificial>:(.text+0xbf8): undefined reference to `main'
<artificial>:(.text+0xcce): undefined reference to `main'
make: *** [/home/nicolas/Téléchargements/SGDK-1.80/makefile_wine.gen:156 : out/rom.out] Erreur 1

I didn't do anything special since yesterday and the 'main' function is referenced correctly. Here's my gist if you have time to take a look : 
https://gist.github.com/nicoco59/ed239c3921ae9e9cc6ccd290936bb026

Thanks in advance for your help.

**Comment by Franticware** [comment]
I am not sure if this would help, but the samples included with the SGDK have main like the following:
int main(bool hard)

Where hard is type of reset and if it is false, some memory might not get initialized by default, if I understand correctly.

**Comment by nicomegadrive** [comment]
I got it to work again, I think that I was executing the command in the Terminal at the wrong place.

Thanks for your help.
